/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Root': RouteRecordInfo<'Root', '/', Record<never, never>, Record<never, never>>,
    'PageNotFound': RouteRecordInfo<'PageNotFound', '/:404(.*)?', { 404?: ParamValueZeroOrOne<true> }, { 404?: ParamValueZeroOrOne<false> }>,
    'Builder': RouteRecordInfo<'Builder', '/builder', Record<never, never>, Record<never, never>>,
    'CharactersParent': RouteRecordInfo<'CharactersParent', '/characters', Record<never, never>, Record<never, never>>,
    'Characters': RouteRecordInfo<'Characters', '/characters', Record<never, never>, Record<never, never>>,
    'CharactersIdParent': RouteRecordInfo<'CharactersIdParent', '/characters/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'CharactersId': RouteRecordInfo<'CharactersId', '/characters/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'CharactersIdCharacteristic': RouteRecordInfo<'CharactersIdCharacteristic', '/characters/:id/characteristic', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'CharactersIdInventory': RouteRecordInfo<'CharactersIdInventory', '/characters/:id/inventory', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'Clans': RouteRecordInfo<'Clans', '/clans', Record<never, never>, Record<never, never>>,
    'ClansId': RouteRecordInfo<'ClansId', '/clans/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ClansIdApplications': RouteRecordInfo<'ClansIdApplications', '/clans/:id/applications', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ClansIdArmory': RouteRecordInfo<'ClansIdArmory', '/clans/:id/armory', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ClansIdUpdate': RouteRecordInfo<'ClansIdUpdate', '/clans/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ClansCreate': RouteRecordInfo<'ClansCreate', '/clans/create', Record<never, never>, Record<never, never>>,
    'Leaderboard': RouteRecordInfo<'Leaderboard', '/leaderboard', Record<never, never>, Record<never, never>>,
    'ModeratorParent': RouteRecordInfo<'ModeratorParent', '/moderator', Record<never, never>, Record<never, never>>,
    'Moderator': RouteRecordInfo<'Moderator', '/moderator', Record<never, never>, Record<never, never>>,
    'ModeratorFindUser': RouteRecordInfo<'ModeratorFindUser', '/moderator/find-user', Record<never, never>, Record<never, never>>,
    'ModeratorUserId': RouteRecordInfo<'ModeratorUserId', '/moderator/user/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ModeratorUserIdActivityLogs': RouteRecordInfo<'ModeratorUserIdActivityLogs', '/moderator/user/:id/activity-logs', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ModeratorUserIdInformation': RouteRecordInfo<'ModeratorUserIdInformation', '/moderator/user/:id/information', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ModeratorUserIdRestrictions': RouteRecordInfo<'ModeratorUserIdRestrictions', '/moderator/user/:id/restrictions', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'PrivacyPolicy': RouteRecordInfo<'PrivacyPolicy', '/privacy-policy', Record<never, never>, Record<never, never>>,
    'Settings': RouteRecordInfo<'Settings', '/settings', Record<never, never>, Record<never, never>>,
    'Shop': RouteRecordInfo<'Shop', '/shop', Record<never, never>, Record<never, never>>,
    'SigninCallback': RouteRecordInfo<'SigninCallback', '/signin-callback', Record<never, never>, Record<never, never>>,
    'Strategus': RouteRecordInfo<'Strategus', '/strategus', Record<never, never>, Record<never, never>>,
  }
}
