export const Longsword = {
  armor: null,
  baseId: 'crpg_sentinel_2hsword_abearirl',
  createdAt: new Date('2023-05-13T21:43:44.0741909Z'),
  culture: 'Neutral',
  flags: ['Civilian'],
  id: 'crpg_sentinel_2hsword_abearirl',
  mount: null,
  name: 'Longsword',
  price: 14117,
  rank: 0,
  requirement: 0,
  tier: 10.046391,
  type: 'TwoHandedWeapon',
  weapons: [
    {
      accuracy: 0,
      balance: 0.2,
      bodyArmor: 5,
      class: 'OneHandedSword',
      flags: ['MeleeWeapon'],
      handling: 64,
      itemUsage: 'onehanded_block_rshield_swing_thrust',
      length: 107,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 39,
      swingDamageType: 'Cut',
      swingSpeed: 75,
      thrustDamage: 19,
      thrustDamageType: 'Pierce',
      thrustSpeed: 84,
    },
    {
      accuracy: 0,
      balance: 0.79,
      bodyArmor: 5,
      class: 'TwoHandedSword',
      flags: ['MeleeWeapon', 'NotUsableWithOneHand'],
      handling: 76,
      itemUsage: 'twohanded_block_swing_thrust',
      length: 107,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 39,
      swingDamageType: 'Cut',
      swingSpeed: 93,
      thrustDamage: 19,
      thrustDamageType: 'Pierce',
      thrustSpeed: 91,
    },
    {
      accuracy: 0,
      balance: 0.2,
      bodyArmor: 5,
      class: 'OneHandedSword',
      flags: ['MeleeWeapon'],
      handling: 64,
      itemUsage: 'onehanded_block_swing_thrust',
      length: 107,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 39,
      swingDamageType: 'Cut',
      swingSpeed: 75,
      thrustDamage: 19,
      thrustDamageType: 'Pierce',
      thrustSpeed: 84,
    },
  ],
  weight: 2.17,
}

export const WoodenSword = {
  armor: null,
  baseId: 'crpg_wooden_sword_t1',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Neutral',
  flags: [],
  id: 'crpg_wooden_sword_t1',
  mount: null,
  name: 'Wooden Sword',
  price: 257,
  rank: 0,
  requirement: 0,
  tier: 1.0245335,
  type: 'OneHandedWeapon',
  weapons: [
    {
      accuracy: 0,
      balance: 0.75,
      bodyArmor: 1,
      class: 'OneHandedSword',
      flags: ['MeleeWeapon', 'NoBlood'],
      handling: 95,
      itemUsage: 'onehanded_block_shield_swing_thrust',
      length: 95,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 10,
      swingDamageType: 'Blunt',
      swingSpeed: 92,
      thrustDamage: 10,
      thrustDamageType: 'Blunt',
      thrustSpeed: 92,
    },
  ],
  weight: 1.42,
}

export const NobleCavalryLance = {
  armor: null,
  baseId: 'crpg_khuzait_lance_3_t5',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Khuzait',
  flags: ['NotStackable'],
  id: 'crpg_khuzait_lance_3_t5',
  mount: null,
  name: 'Noble Cavalry Lance',
  price: 2593,
  rank: 0,
  requirement: 0,
  tier: 3.7166684,
  type: 'Polearm',
  weapons: [
    {
      accuracy: 0,
      balance: 0,
      bodyArmor: 0,
      class: 'OneHandedPolearm',
      flags: ['MeleeWeapon', 'WideGrip'],
      handling: 62,
      itemUsage: 'onehanded_polearm_block_long_rshield_thrust',
      length: 200,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 18,
      thrustDamage: 25,
      thrustDamageType: 'Pierce',
      thrustSpeed: 82,
    },
    {
      accuracy: 0,
      balance: 0,
      bodyArmor: 0,
      class: 'TwoHandedPolearm',
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      handling: 58,
      itemUsage: 'polearm_block_long_shield_thrust',
      length: 200,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 68,
      thrustDamage: 25,
      thrustDamageType: 'Pierce',
      thrustSpeed: 91,
    },
    {
      accuracy: 0,
      balance: 0,
      bodyArmor: 0,
      class: 'TwoHandedPolearm',
      flags: ['MeleeWeapon', 'WideGrip'],
      handling: 62,
      itemUsage: 'polearm_couch',
      length: 200,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 18,
      thrustDamage: 25,
      thrustDamageType: 'Pierce',
      thrustSpeed: 82,
    },
  ],
  weight: 2.03,
}

export const BecDeCorbin = {
  armor: null,
  baseId: 'crpg_bec_de_corbin',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Neutral',
  flags: ['CanBePickedUpFromCorpse'],
  id: 'crpg_bec_de_corbin',
  mount: null,
  name: 'Bec De Corbin',
  price: 14020,
  rank: 0,
  requirement: 0,
  tier: 10.008125,
  type: 'Polearm',
  weapons: [
    {
      accuracy: 0,
      balance: 0.4,
      bodyArmor: 0,
      class: 'TwoHandedPolearm',
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      handling: 70,
      itemUsage: 'polearm_block_long_shield_swing_thrust',
      length: 139,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 29,
      swingDamageType: 'Pierce',
      swingSpeed: 82,
      thrustDamage: 27,
      thrustDamageType: 'Pierce',
      thrustSpeed: 92,
    },
  ],
  weight: 2.11,
}

export const SimpleShortSpear = {
  armor: null,
  baseId: 'crpg_western_spear_2_t2',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Vlandia',
  flags: [],
  id: 'crpg_western_spear_2_t2',
  mount: null,
  name: 'Simple Short Spear',
  price: 1875,
  rank: 0,
  requirement: 0,
  tier: 3.0168896,
  type: 'Polearm',
  weapons: [
    {
      accuracy: 0,
      balance: 0,
      bodyArmor: 0,
      class: 'OneHandedPolearm',
      flags: ['MeleeWeapon', 'WideGrip'],
      handling: 72,
      itemUsage: 'onehanded_polearm_block_long_rshield_thrust',
      length: 156,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 16,
      swingDamageType: 'Blunt',
      swingSpeed: 49,
      thrustDamage: 22,
      thrustDamageType: 'Pierce',
      thrustSpeed: 92,
    },
    {
      accuracy: 0,
      balance: 0.58,
      bodyArmor: 0,
      class: 'TwoHandedPolearm',
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      handling: 70,
      itemUsage: 'polearm_block_long_shield_swing_thrust',
      length: 156,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 16,
      swingDamageType: 'Blunt',
      swingSpeed: 87,
      thrustDamage: 22,
      thrustDamageType: 'Pierce',
      thrustSpeed: 99,
    },
    {
      accuracy: 0,
      balance: 0.58,
      bodyArmor: 0,
      class: 'TwoHandedPolearm',
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      handling: 70,
      itemUsage: 'polearm_block_long_shield_thrust',
      length: 156,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 16,
      swingDamageType: 'Blunt',
      swingSpeed: 87,
      thrustDamage: 22,
      thrustDamageType: 'Pierce',
      thrustSpeed: 99,
    },
  ],
  weight: 1.08,
}

export const Pike = {
  armor: null,
  baseId: 'crpg_vlandia_pike_1_t5',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Vlandia',
  flags: ['DropOnWeaponChange', 'TestFlag'],
  id: 'crpg_vlandia_pike_1_t5',
  mount: null,
  name: 'Pike',
  price: 3547,
  rank: 0,
  requirement: 0,
  tier: 4.1352773,
  type: 'Polearm',
  weapons: [
    {
      accuracy: 0,
      balance: 0,
      bodyArmor: 0,
      class: 'TwoHandedPolearm',
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount', 'TestFlag'],
      handling: 34,
      itemUsage: 'polearm_pike',
      length: 501,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 22,
      thrustDamage: 21,
      thrustDamageType: 'Pierce',
      thrustSpeed: 86,
    },
    {
      accuracy: 0,
      balance: 0,
      bodyArmor: 0,
      class: 'TwoHandedPolearm',
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      handling: 34,
      itemUsage: 'polearm_bracing',
      length: 501,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 22,
      thrustDamage: 21,
      thrustDamageType: 'Pierce',
      thrustSpeed: 86,
    },
  ],
  weight: 1.07,
}

export const Hoe = {
  armor: null,
  baseId: 'crpg_peasant_2haxe_1_t1',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Neutral',
  flags: ['CanBePickedUpFromCorpse', 'Civilian'],
  id: 'crpg_peasant_2haxe_1_t1',
  mount: null,
  name: 'Hoe',
  price: 677,
  rank: 0,
  requirement: 0,
  tier: 1.462035,
  type: 'TwoHandedWeapon',
  weapons: [
    {
      accuracy: 0,
      balance: 0.33,
      bodyArmor: 0,
      class: 'OneHandedAxe',
      flags: ['MeleeWeapon', 'BonusAgainstShield'],
      handling: 77,
      itemUsage: 'onehanded_rshield_axe',
      length: 92,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 24,
      swingDamageType: 'Cut',
      swingSpeed: 79,
      thrustDamage: 0,
      thrustDamageType: 'Undefined',
      thrustSpeed: 92,
    },
    {
      accuracy: 0,
      balance: 0.88,
      bodyArmor: 0,
      class: 'TwoHandedAxe',
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'BonusAgainstShield', 'TwoHandIdleOnMount'],
      handling: 85,
      itemUsage: 'twohanded_axe',
      length: 92,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 24,
      swingDamageType: 'Cut',
      swingSpeed: 96,
      thrustDamage: 0,
      thrustDamageType: 'Undefined',
      thrustSpeed: 99,
    },
    {
      accuracy: 0,
      balance: 0.33,
      bodyArmor: 0,
      class: 'OneHandedAxe',
      flags: ['MeleeWeapon', 'BonusAgainstShield'],
      handling: 77,
      itemUsage: 'onehanded_axe',
      length: 92,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 24,
      swingDamageType: 'Cut',
      swingSpeed: 79,
      thrustDamage: 0,
      thrustDamageType: 'Undefined',
      thrustSpeed: 92,
    },
  ],
  weight: 1.27,
}

export const Shield = {
  armor: null,
  baseId: 'crpg_oval_shield',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Aserai',
  flags: ['ForceAttachOffHandSecondaryItemBone', 'WoodenParry', 'HeldInOffHand'],
  id: 'crpg_oval_shield',
  mount: null,
  name: 'Wooden Oval Shield',
  price: 2820,
  rank: 0,
  requirement: 0,
  tier: 5.043636,
  type: 'Shield',
  weapons: [
    {
      accuracy: 100,
      balance: 0,
      bodyArmor: 0,
      class: 'LargeShield',
      flags: ['HasHitPoints', 'CanBlockRanged'],
      handling: 82,
      itemUsage: 'shield',
      length: 132,
      missileSpeed: 0,
      stackAmount: 70,
      swingDamage: 0,
      swingDamageType: 'Blunt',
      swingSpeed: 82,
      thrustDamage: 0,
      thrustDamageType: 'Blunt',
      thrustSpeed: 82,
    },
  ],
  weight: 11.6,
}

export const Bow = {
  armor: null,
  baseId: 'crpg_noble_bow',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Neutral',
  flags: ['ForceAttachOffHandPrimaryItemBone'],
  id: 'crpg_noble_bow',
  mount: null,
  name: 'Noble Bow',
  price: 12133,
  rank: 0,
  requirement: 0,
  tier: 9.940793,
  type: 'Bow',
  weapons: [
    {
      accuracy: 95,
      balance: 0,
      bodyArmor: 0,
      class: 'Bow',
      flags: [
        'RangedWeapon',
        'NotUsableWithOneHand',
        'HasString',
        'StringHeldByHand',
        'UnloadWhenSheathed',
        'AutoReload',
        'TwoHandIdleOnMount',
      ],
      handling: 100,
      itemUsage: 'bow',
      length: 116,
      missileSpeed: 85,
      stackAmount: 1,
      swingDamage: 0,
      swingDamageType: 'Blunt',
      swingSpeed: 98,
      thrustDamage: 14,
      thrustDamageType: 'Pierce',
      thrustSpeed: 100,
    },
  ],
  weight: 0.4,
}

export const Bolts = {
  armor: null,
  baseId: 'crpg_bolt_f',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Empire',
  flags: ['ForceAttachOffHandPrimaryItemBone'],
  id: 'crpg_bolt_f',
  mount: null,
  name: 'Heavy Piercing Bolts',
  price: 7815,
  rank: 0,
  requirement: 0,
  tier: 9.736687,
  type: 'Bolts',
  weapons: [
    {
      accuracy: 100,
      balance: 0,
      bodyArmor: 0,
      class: 'Bolt',
      flags: ['AttachAmmoToVisual', 'Consumable'],
      handling: 0,
      itemUsage: '',
      length: 37,
      missileSpeed: 10,
      stackAmount: 5,
      swingDamage: 0,
      swingDamageType: 'Blunt',
      swingSpeed: 0,
      thrustDamage: 14,
      thrustDamageType: 'Pierce',
      thrustSpeed: 0,
    },
  ],
  weight: 0.3,
}

export const ThrowingAxe = {
  armor: null,
  baseId: 'crpg_western_throwing_axe_1_t1',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Vlandia',
  flags: ['CanBePickedUpFromCorpse'],
  id: 'crpg_western_throwing_axe_1_t1',
  mount: null,
  name: 'Francesca',
  price: 2300,
  rank: 0,
  requirement: 0,
  tier: 5.093825,
  type: 'Thrown',
  weapons: [
    {
      accuracy: 0,
      balance: 1,
      bodyArmor: 0,
      class: 'OneHandedAxe',
      flags: ['MeleeWeapon', 'BonusAgainstShield'],
      handling: 108,
      itemUsage: 'onehanded_shield_axe',
      length: 38,
      missileSpeed: 0,
      stackAmount: 0,
      swingDamage: 11,
      swingDamageType: 'Cut',
      swingSpeed: 111,
      thrustDamage: 0,
      thrustDamageType: 'Undefined',
      thrustSpeed: 94,
    },
    {
      accuracy: 93,
      balance: 1,
      bodyArmor: 0,
      class: 'ThrowingAxe',
      flags: [
        'RangedWeapon',
        'Consumable',
        'UnloadWhenSheathed',
        'BonusAgainstShield',
        'AutoReload',
        'AmmoBreaksOnBounceBack',
      ],
      handling: 108,
      itemUsage: 'throwing_axe',
      length: 38,
      missileSpeed: 25,
      stackAmount: 3,
      swingDamage: 0,
      swingDamageType: 'Cut',
      swingSpeed: 111,
      thrustDamage: 32,
      thrustDamageType: 'Undefined',
      thrustSpeed: 94,
    },
  ],
  weight: 1.25,
}

export const MountHarness = {
  armor: {
    armArmor: 0,
    bodyArmor: 6,
    familyType: 1,
    headArmor: 0,
    legArmor: 0,
    materialType: 'Leather',
  },
  baseId: 'crpg_light_harness',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Neutral',
  flags: ['Civilian'],
  id: 'crpg_light_harness',
  mount: null,
  name: 'Light Harness',
  price: 1712,
  rank: 0,
  requirement: 0,
  tier: 1.3333334,
  type: 'MountHarness',
  weapons: [],
  weight: 20,
}

export const Mount = {
  armor: null,
  baseId: 'crpg_mount_balanced_5',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Khuzait',
  flags: ['Civilian'],
  id: 'crpg_mount_balanced_5',
  mount: {
    bodyLength: 105,
    chargeDamage: 1,
    familyType: 1,
    hitPoints: 172,
    maneuver: 66,
    speed: 40,
  },
  name: 'Murgese Rouncey',
  price: 5384,
  rank: 0,
  requirement: 0,
  tier: 4.998832,
  type: 'Mount',
  weapons: [],
  weight: 450,
}

export const Helmet = {
  armor: {
    armArmor: 0,
    bodyArmor: 0,
    familyType: 0,
    headArmor: 64,
    legArmor: 0,
    materialType: 'Plate',
  },
  baseId: 'crpg_sa_1ChurburghHelm',
  createdAt: new Date('2023-07-13T21:43:44.0741909Z'),
  culture: 'Vlandia',
  flags: [],
  id: 'crpg_sa_1ChurburghHelm',
  mount: null,
  name: 'Hounskull Bascinet',
  price: 14334,
  rank: 0,
  requirement: 0,
  tier: 9.969065,
  type: 'HeadArmor',
  weapons: [],
  weight: 4.64,
}
